#!/usr/bin/env python
'''
Hobo.

Usage:
    hobo (up | start) [<name> --gui]
    hobo (down | stop) [<name>]
    hobo pause
    hobo ssh
    hobo ip
    hobo list
    hobo -h | --help
    hobo --version

Options:
    -h --help     Show this screen.
    --version     Show version.
'''
from clint.textui import colored, puts
from docopt import docopt
from vmrun import Vmrun
import glob
import os

def get_vmx():
    files = glob.glob('*.vmx')
    if files:
        return files[0]
    raise IOError

if __name__ == '__main__':
    arguments = docopt(__doc__, version='hobo 0.1')

    if arguments['list']:
        vm = Vmrun('')
        puts("".join(vm.list()))
        exit()

    vm = arguments['<name>'] if arguments['<name>'] else get_vmx()
    vm = Vmrun(vm, user='user', password='user', debug=True)

    if arguments['up'] or arguments['start']:
        puts(colored.yellow("Starting", vm))
        if arguments['--gui']:
            vm.start(gui=True)
        else:
            vm.start()

    if arguments['down'] or arguments['stop']:
        puts(colored.yellow("Stopping", vm))
        vm.stop()

    if arguments['pause']:
        puts(colored.yellow("Stopping", vm))
        vm.pause()

    if arguments['ssh']:
        ip = vm.ip()
        if ip:
            puts(colored.green(ip))
            os.system('ssh user@{}'.format(ip))
        else:
            puts(colored.red("IP not found, could not SSH "))

    if arguments['ip']:
        ip = vm.ip()
        if ip:
            puts(ip)
        else:
            puts(colored.red("IP not found"))
